# File: .github/workflows/workflow.yml

on: [push]

name: Stop Trigger Synapse

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    - name: Install the powershell dependencies
      shell: pwsh
      run: |
        Install-Module -Name Az.Synapse -AllowClobber -Scope CurrentUser -Force
        Import-Module Az.Synapse

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure PowerShell Action
      uses: Azure/powershell@v1.4.0
      with:
        inlineScript: ./Stop_Triggers.ps1
        azPSVersion: "latest"

    # - name: Run the script as Adminstrator
    #   shell: pwsh
    #   run: |
    #     $scriptPath = "Stop_Triggers.ps1"
    #     pwsh -ExecutionPolicy Bypass -File $scriptPath
