name: Synapse_Triggers_Annotations
on: [push]
# on: 
# workflow_dispatch
jobs:
  release:
    runs-on: windows-latest
    env:
      SynapseWorkspace: "testtriggerautomate"
      ResourceGroup: "RG-Metrolinx"
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: Install the powershell dependencies and run script
        shell: pwsh
        run: |
          Install-Module -Name Az.Synapse -AllowClobber -Scope CurrentUser -Force
          Import-Module Az.Synapse
          $ResourceGroupName = '${{ env.ResourceGroup }}'
          $SynapseWorkspace = '${{ env.SynapseWorkspace }}'
          $workspace = Get-AzSynapseWorkspace -ResourceGroupName $ResourceGroupName -Name $SynapseWorkspace
          $Triggers = Get-AzSynapseTrigger -WorkspaceObject $workspace
          #$stoppedTriggers = $Triggers | Where-Object { $_.Properties.RuntimeState -eq "Stopped" }
          $startedTriggers = @()
          foreach ($trigger in $Triggers) {
          Write-Host "Start"
          $trigger.Name
           if($Trigger.Properties.RuntimeState -eq "Started")
              {
              Stop-AzSynapseTrigger -WorkspaceName $SynapseWorkspace -Name $trigger.Name
              $startedTriggers += $trigger.Name
              Write-Host "Stopped trigger $($trigger.Name)."
          } elseif ($Trigger.Properties.RuntimeState -eq "Stopped") {
              Write-Host "Trigger $($trigger.Name) is already in a stopped state."
          }
          }
          $jsonString = ConvertTo-Json -InputObject $startedTriggers
          Out-File -FilePath "started_triggers.json" -InputObject $jsonString
          # foreach ($triggerName in $startedTriggers) {
          #     # Start-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $triggerName
          #     Start-AzSynapseTrigger -WorkspaceName $SynapseWorkspace -Name $triggerName
          #     Write-Host "Started trigger $triggerName."
          # }


      - uses: actions/upload-artifact@v3
        with:
          name: started-triggers
          path: started_triggers.json
      - name: Download artifact and access array
        uses: actions/download-artifact@v3
        with:
          name: started-triggers
      - name: run script
        shell: pwsh
        run: |
          Install-Module -Name Az.Synapse -AllowClobber -Scope CurrentUser -Force
          Import-Module Az.Synapse
          $ResourceGroupName = '${{ env.ResourceGroup }}'
          $SynapseWorkspace = '${{ env.SynapseWorkspace }}'
          $workspace = Get-AzSynapseWorkspace -ResourceGroupName $ResourceGroupName -Name $SynapseWorkspace
          $Triggers = Get-AzSynapseTrigger -WorkspaceObject $workspace
          #$stoppedTriggers = $Triggers | Where-Object { $_.Properties.RuntimeState -eq "Stopped" }
          $triggertostop = Get-Content -Path "started_triggers.json"
          echo "-----list-json-file-----"
          Tree /F
          cat D:\a\GitHubActionsDemo\GitHubActionsDemo\started_trigger.json
          echo $triggertostop
          foreach ($triggerName in $triggertostop) {
              # Start-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $triggerName
              Start-AzSynapseTrigger -WorkspaceName $SynapseWorkspace -Name $triggerName
              Write-Host "Started trigger $triggerName."
          }
