name: Synapse_Triggers_Annotations
on: [push]
# on: 
#  workflow_dispatch

jobs:
  release:
    runs-on: windows-latest
    env:
      SynapseWorkspace: "testtriggerautomate"
      ResourceGroup: "RG-Metrolinx"
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Install the powershell dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az.Synapse -AllowClobber -Scope CurrentUser -Force
          Import-Module Az.Synapse 

      # - uses: actions/checkout@v1 
      # - name: Run a one-line script
      #   shell: powershell
      #   run: |
      #     $scriptPath = "Triggers_Annotations.ps1"
      #     pwsh -ExecutionPolicy Bypass -File $scriptPath

      # - uses: actions/checkout@v1 
      # - name: Run a one-line script
      #   shell: powershell
      #   run: |
      #     $scriptPath = "Triggers_Annotations_Start.ps1"
      #     pwsh -ExecutionPolicy Bypass -File $scriptPath  


      - name: Azure CLI Action
        uses: Azure/cli@v1.0.9
        with:
          azcliversion: "latest"
          inlineScript: |
            # $ResourceGroupName = "RG-Metrolinx"
            # $SynapseWorkspace = “testtriggerautomate”

            # $workspace = Get-AzSynapseWorkspace -ResourceGroupName $ResourceGroupName -Name $SynapseWorkspace
            # $Triggers = Get-AzSynapseTrigger -WorkspaceObject $workspace

            # #$stoppedTriggers = $Triggers | Where-Object { $_.Properties.RuntimeState -eq "Stopped" }

            # $startedTriggers = @()

            # foreach ($trigger in $Triggers) {
            # Write-Host "Start"
            # $trigger.Name
            #  if($Trigger.Properties.RuntimeState -eq "Started")
            #     {
            #     Stop-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $trigger.Name
            #     $startedTriggers += $trigger.Name
            #     Write-Host "Stopped trigger $($trigger.Name)."
            # } elseif ($Trigger.Properties.RuntimeState -eq "Stopped") {
            #     Write-Host "Trigger $($trigger.Name) is already in a stopped state."
            # }
            # }


            # foreach ($triggerName in $startedTriggers) {
            #     Start-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $triggerName
            #     Write-Host "Started trigger $triggerName."
            # }
            Stop-AzSynapseTrigger -WorkspaceName "testtriggerautomate" -Name "Trigger 1"
            Stop-AzSynapseTrigger -WorkspaceName "testtriggerautomate" -Name "Trigger 3"
            
