name: Dev_Start_Stop_Synapse_Triggers
on: [push]
env:
  clientAppId: '${{ secrets.CLIENT_ID }}'
  clientAppSecret: '${{ secrets.CLIENT_SECRET }}'
  subscriptionId: '${{ secrets.SUBSCRIPTION_ID}}'
  tenantId: '${{ secrets.TENANT_ID}}'
  TargetResourceGroup: "RG-Metrolinx"
  TargetWorkspaceName: "testtriggerautomate"
jobs:
  release:
    runs-on: windows-latest
    environment: dev
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Install the powershell dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az.Synapse -AllowClobber -Scope CurrentUser -Force
          Import-Module Az.Synapse

      - name: Synapse Start Dev Trigger 
        run: |
         # foreach($file in Get-ChildItem -Path ${{ env.artifactDirectory }}\${{ env.triggerPath }}\*.json -Name)
         # {
         #   $trigger = Get-Content -Raw ${{ env.artifactDirectory }}\${{ env.triggerPath }}\$file | ConvertFrom-Json  
         #   if(([string](az synapse trigger list --workspace-name ${{ vars.MX_SYNAPSE_WORKSPACE }} --query [].name) -match $trigger.name))
         #   {
         #     az synapse trigger start --workspace-name ${{ vars.MX_SYNAPSE_WORKSPACE }} --name $trigger.name
         #     #az synapse trigger resume --workspace-name  ${{ vars.MX_SYNAPSE_WORKSPACE }} --name $trigger.name
         #     echo "Trigger started"$trigger.name
         #   }          
         # }
         # Get the specified workspace
         Write-Output ("Getting workspace {0} in resource group {1}" -f $synapseworkspace, $resourcegroup)
         $workspace = Get-AzSynapseWorkspace -ResourceGroupName $resourcegroup -Name $synapseworkspace
         if (-not($workspace)) { throw "Could not find workspace" }
         Write-Output $workspace
