name: Synapse_Triggers_Annotations
on: [push]
# on: 
# workflow_dispatch

jobs:
  release:
    runs-on: windows-latest
    # env:
    #   SynapseWorkspace: "testtriggerautomate"
    #   ResourceGroup: "RG-Metrolinx"
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Install the powershell dependencies and run script
        shell: pwsh
        run: |
          Install-Module -Name Az.Synapse -AllowClobber -Scope CurrentUser -Force
          Import-Module Az.Synapse

          # $ResourceGroupName = "RG-Metrolinx"
          # $SynapseWorkspace = “testtriggerautomate”
          $ResourceGroupName = "${{ vars.devtest.RESOURCEGROUP }}"
          $SynapseWorkspace = “${{ vars.devtest.SYNAPSEWORKSPACE }}”

          $workspace = Get-AzSynapseWorkspace -ResourceGroupName ${{ vars.devtest.RESOURCEGROUP }} -Name ${{ vars.devtest.SYNAPSEWORKSPACE }}
          $Triggers = Get-AzSynapseTrigger -WorkspaceObject $workspace

          #$stoppedTriggers = $Triggers | Where-Object { $_.Properties.RuntimeState -eq "Stopped" }

          $startedTriggers = @()

          foreach ($trigger in $Triggers) {
          Write-Host "Start"
          $trigger.Name
           if($Trigger.Properties.RuntimeState -eq "Started")
              {
              Stop-AzSynapseTrigger -WorkspaceName ${{ vars.devtest.SYNAPSEWORKSPACE }} -Name $trigger.Name
              $startedTriggers += $trigger.Name
              Write-Host "Stopped trigger $($trigger.Name)."
          } elseif ($Trigger.Properties.RuntimeState -eq "Stopped") {
              Write-Host "Trigger $($trigger.Name) is already in a stopped state."
          }
          }

          foreach ($triggerName in $startedTriggers) {
              # Start-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $triggerName
              Start-AzSynapseTrigger -WorkspaceName ${{ vars.devtest.SYNAPSEWORKSPACE }} -Name $triggerName
              Write-Host "Started trigger $triggerName."
          }
