name: Dev_Start_Synapse_Triggers
on: [push]
env:
  clientAppId: '${{ secrets.CLIENT_ID }}'
  clientAppSecret: '${{ secrets.CLIENT_SECRET }}'
  subscriptionId: '${{ secrets.SUBSCRIPTION_ID}}'
  tenantId: '${{ secrets.TENANT_ID}}'
  resourcegroup: "RG-Metrolinx"
  synapseworkspace: "testtriggerautomate"
jobs:
  release:
    runs-on: windows-latest
    environment: dev
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Install the powershell dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az.Synapse -AllowClobber -Scope CurrentUser -Force
          Import-Module Az.Synapse 

      - uses: actions/checkout@v1 
      - name: Run a one-line script
        shell: powershell
        run: |
          $synapseworkspace = "${{ vars.synapseworkspace }}"
          $resourcegroup = "${{ vars.resourcegroup }}"
          $scriptPath = "Start_Triggers.ps1"
          pwsh -ExecutionPolicy Bypass -File $scriptPath

